name: CI

on:
  push:
    paths:
    - '**.js'
    - '**.vue'
    - '**.json'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: Run frontend lint tests
        run: |
          cd ./frontend
          npm install
          npm run lint
          cd ..
      - name: Run backend lint tests
        run: |
          cd ./backend
          npm install
          npm run lint
          cd ..
  buildFront:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: Installing project dependencies
        working-directory: ./frontend
        run: npm install
      - name: Building the project
        working-directory: ./frontend
        run: npm run build
        env:
          VUE_APP_HOST_API: ${{ secrets.VUE_APP_HOST_API }}
          VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}
      - name: 'Saving build'
        uses: actions/upload-artifact@v2
        with:
          name: front
          path: dist
      
  build:
    needs: buildFront
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v2
        with:
          name: front
          path: ./backend/public
      # Builds docker image
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            JOB_NUMBER=${{ github.run_id }}
            SHA=${{ github.sha }}
          context: ./backend
          file: ./backend/Dockerfile
          tags: silvafacundo/sip2021-coloncafebar:latest, silvafacundo/sip2021-coloncafebar:${{ github.sha }}
     
