# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: Installing project dependencies
        working-directory: ./frontend
        run: npm install
      - name: Building the project
        working-directory: ./frontend
        run: npm run build
        env:
          VUE_APP_HOST_API: ${{ secrets.VUE_APP_HOST_API }}
          VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}

  publish_docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Builds docker image
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile
          tags: silvafacundo/sip2021-coloncafebar:latest, silvafacundo/sip2021-coloncafebar:${{ github.sha }}
